### ISSUE TITLE
Do not advertise heroku pinger

### ISSUE THREAD

**Issue by sander1095** [inoda/ontrack#24]
Hi!

I see you adverise heroku pinger in your readme.

I would suggest removing that. Heroku is free and stays free (and awesome) because of the limits in place. Using a tool like heroku pinger can only result in Heroku setting more constraints.

**Comment by inoda** [comment]
@sander1095 I don't think Heroku pinger violates any terms. All it does is make keeps your Heroku app awake during a window of time that is within the limits of Heroku's free dyno usage. It's just the same as having a free dyno running that gets 1 visitor every 30 mins, which isn't unreasonable. If you have some Heroku knowledge that says otherwise, I'm happy to make that repo private and not advertise it. Closing the issue for now.

> Heroku also caps free dyno usage so that your dyno can't be awake 24/7. This app allows you to set a window where pinging your application is paused (your app probably doesn't need to stay awake while you're sleeping).
