### ISSUE TITLE
Widnows

### ISSUE THREAD

**Issue by fezix** [inoda/ontrack#98]
Hello, how do I run this app on windows?

**Comment by mzygadlo** [comment]
Hi @fezix,

You have a few options:
- run it via Docker 
- install the Windows Subsystem for Linux ([here is tutorial](https://gorails.com/setup/windows/10))
- install Ruby on Windows with [Ruby Installer](https://rubyinstaller.org/downloads/)

The last one can be harder - some gems may not work because of a different system architecture .
